name = "LeftRight"
uuid = "78a604cf-3861-458a-9dc0-49592e8d97d7"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
UnsafeAtomics = "013be700-e6cd-48c3-b4a1-df204f14c38f"

[compat]
UnsafeAtomics = "0.1"
julia = "1.7"
